### ISSUE TITLE
inspectAugment.py

### ISSUE THREAD

**Issue by sara-kassani** [AlexanderRadovic/KaggleDataScienceBowl2018#1]
Hello,
inspectAugment.py file is not uploaded into the repository.

Thanks

**Comment by AlexanderRadovic** [comment]
Hey Sara,

Good catch! I forgot to update the README when I removed it. Most of its code was actually already in testgenerator so I just combined the two. I hope that helps, let me know if you have any other questions!

Best,
-Alex
